### ISSUE TITLE
main.py貌似不能用了

### ISSUE THREAD

**Issue by LouShuaitong** [tignioj/test_login#1]
问卷地址：https://www.wjx.cn/jq/29069318.aspx
问卷统计信息： https://www.wjx.cn/report/29069318.aspx
你好，参考main.py代码测试了一下，发现能顺利提交，服务器响应200，但是问卷星后台不统计。
能否有时间再更新下？
代码如下：
```
import sys
import requests
import time
import datetime
from random import randint
import urllib3
import re
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
import requests
import random

def post_wjx():
    #需要需改的参数
    #1, curlID, 
    #2,CookitText, 
    #3, return_random_data()函数里面的返回的数据
    curID ='29069318'
    submitdata = "1$2}2$2}3$2}4$1!4,2!5,3!6"
    #submitdata ={
    #    "submitdata": return_random_data()
    #}
    s = (datetime.datetime.now()-datetime.timedelta(minutes=1)).strftime("%Y/%m/%d %H:%M:%S") #后退一分钟，wjx禁止填写问卷时间过短
    ss = s[:5] + s[6:] #去掉月份开头的0
    postURL = 'https://www.wjx.cn/joinnew/processjq.ashx' #提交的地址
    myurl = "https://www.wjx.cn/jq/"+curID+".aspx"
    
    getrnnum = requests.get(url=myurl, verify=False)
    rn = re.findall(r'rndnum="(\d+\.?\d+)"', getrnnum.text)
	#jacnumber = getrnnum.headers['Set-Cookie'] 
    FormData = {
        'submittype': '1',
        'curID' : curID,
        't' : str(int(time.time()*1000)),
        'starttime' : ss,#时间可以抓包从js脚本中获取，也可以用python生成
        'rn' : rn[0],#抓js
        'hlv' : '1'
    }
    timep = str(int(time.time()))
    #这个是关键，先电脑提交一次然后Fiddler抓包https://www.wjx.cn/joinnew/processjq.ashx这个网址的提交的Cookie并且复制下来,把后面的十个数字去掉,由timep时间戳生成
    CookieText = "actidev_26045045=1; UM_distinctid=166611f8cdfb1-0b9d2021ceb2ff-7047503f-100200-166611f8ce0a5; CNZZDATA4478442=cnzz_eid%3D1287161973-1539224235-%26ntime%3D1539245835; .ASPXANONYMOUS=c1CZi6KX1AEkAAAANzA1YjJmYWMtOWM3ZS00Yjc1LTg2ZjgtNWMzZmFiM2UxZWIyBZNWWYpgQfYns8joBOxaFHemPnI1; acw_tc=707c9fda15392277486277158e44c95ca586597bc4e8a4762b8a06e9022f28; jac29052623=12358503; Hm_lvt_21be24c80829bd7a683b2c536fcf520b=1539227750,1539250329; Hm_lpvt_21be24c80829bd7a683b2c536fcf520b=" + timep
    headers = {
        "Host": "www.wjx.cn",
        "Connection": "Keep-Alive",
        "Content-Length": "72",
        "Origin": "https://www.wjx.cn",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299",
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "zh-CN",
        "Referer": "https://www.wjx.cn/jq/"+curID+".aspx",
        #随机ip绕过wjx验证码机制（同一ip短时间内提交多次需要验证码）
        'X-Forwarded-For' : str(randint(1,255)) + '.' + str(randint(1,255)) + '.' + str(randint(1,255)) + '.' + str(randint(1,255)), 
        "Cookie": CookieText
    }


    r = requests.post(url=postURL,params=FormData, headers=headers, data=submitdata, verify=False)
    print(r)
    print(rn)


times=1
#while(times <= int(sys.argv[1])):
while(times <= 5):
    post_wjx() 
    times+=1
```

**Comment by tignioj** [comment]
### 已经更新，你试下新版
另外不能单纯的看响应来判断是否提交成功，应该看响应的内容`r.text`是否有`complete`的字样，
- 如果`r.text`是22, 那么很有可能就是问卷的Cookie 出错,
- 如果问卷本身自带答题界面从一开始就有验证码，或者换ip验证码也不消失，请删掉问卷重新复制一份
- 如果问卷不带验证码，而响应要求验证码，也应该是Cookie 的问题。
- 解决Cookie的问题就需要抓包，看浏览器怎么提交的，模仿浏览器去提交Cookie
### 新版本`main.py`有随机生成答案的特新，你可以试下，有需要适配的题型可以附上问卷地址

**Comment by tignioj** [comment]
> 问卷地址：https://www.wjx.cn/jq/29069318.aspx
> 问卷统计信息： https://www.wjx.cn/report/29069318.aspx
> 你好，参考main.py代码测试了一下，发现能顺利提交，服务器响应200，但是问卷星后台不统计。
> 能否有时间再更新下？
> 代码如下：
> 
> ```
> import sys
> import requests
> import time
> import datetime
> from random import randint
> import urllib3
> import re
> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
> import requests
> import random
> 
> def post_wjx():
>     #需要需改的参数
>     #1, curlID, 
>     #2,CookitText, 
>     #3, return_random_data()函数里面的返回的数据
>     curID ='29069318'
>     submitdata = "1$2}2$2}3$2}4$1!4,2!5,3!6"
>     #submitdata ={
>     #    "submitdata": return_random_data()
>     #}
>     s = (datetime.datetime.now()-datetime.timedelta(minutes=1)).strftime("%Y/%m/%d %H:%M:%S") #后退一分钟，wjx禁止填写问卷时间过短
>     ss = s[:5] + s[6:] #去掉月份开头的0
>     postURL = 'https://www.wjx.cn/joinnew/processjq.ashx' #提交的地址
>     myurl = "https://www.wjx.cn/jq/"+curID+".aspx"
>     
>     getrnnum = requests.get(url=myurl, verify=False)
>     rn = re.findall(r'rndnum="(\d+\.?\d+)"', getrnnum.text)
> 	#jacnumber = getrnnum.headers['Set-Cookie'] 
>     FormData = {
>         'submittype': '1',
>         'curID' : curID,
>         't' : str(int(time.time()*1000)),
>         'starttime' : ss,#时间可以抓包从js脚本中获取，也可以用python生成
>         'rn' : rn[0],#抓js
>         'hlv' : '1'
>     }
>     timep = str(int(time.time()))
>     #这个是关键，先电脑提交一次然后Fiddler抓包https://www.wjx.cn/joinnew/processjq.ashx这个网址的提交的Cookie并且复制下来,把后面的十个数字去掉,由timep时间戳生成
>     CookieText = "actidev_26045045=1; UM_distinctid=166611f8cdfb1-0b9d2021ceb2ff-7047503f-100200-166611f8ce0a5; CNZZDATA4478442=cnzz_eid%3D1287161973-1539224235-%26ntime%3D1539245835; .ASPXANONYMOUS=c1CZi6KX1AEkAAAANzA1YjJmYWMtOWM3ZS00Yjc1LTg2ZjgtNWMzZmFiM2UxZWIyBZNWWYpgQfYns8joBOxaFHemPnI1; acw_tc=707c9fda15392277486277158e44c95ca586597bc4e8a4762b8a06e9022f28; jac29052623=12358503; Hm_lvt_21be24c80829bd7a683b2c536fcf520b=1539227750,1539250329; Hm_lpvt_21be24c80829bd7a683b2c536fcf520b=" + timep
>     headers = {
>         "Host": "www.wjx.cn",
>         "Connection": "Keep-Alive",
>         "Content-Length": "72",
>         "Origin": "https://www.wjx.cn",
>         "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299",
>         "Content-Type": "application/x-www-form-urlencoded",
>         "Accept": "*/*",
>         "Accept-Encoding": "gzip, deflate, br",
>         "Accept-Language": "zh-CN",
>         "Referer": "https://www.wjx.cn/jq/"+curID+".aspx",
>         #随机ip绕过wjx验证码机制（同一ip短时间内提交多次需要验证码）
>         'X-Forwarded-For' : str(randint(1,255)) + '.' + str(randint(1,255)) + '.' + str(randint(1,255)) + '.' + str(randint(1,255)), 
>         "Cookie": CookieText
>     }
> 
> 
>     r = requests.post(url=postURL,params=FormData, headers=headers, data=submitdata, verify=False)
>     print(r)
>     print(rn)
> 
> 
> times=1
> #while(times <= int(sys.argv[1])):
> while(times <= 5):
>     post_wjx() 
>     times+=1
> ```

如上

**Comment by LouShuaitong** [comment]
发现是Cookie没抓取好。
**非常感谢，测试已经可以用了**
